# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: node:lts

# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

# before_script:
#   - echo "Before script section"
#   - echo "For example you might run an update here or install a build dependency"
#   - echo "Or perhaps you might print out some debugging details"

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"


stages:
  - build

build:
  stage: build
  tags: 
    - node
  only:
    - master
  cache:
    paths:
      - .cache/
  before_script:
    - mkdir -p .cache
    - npm config set cache $CI_PROJECT_DIR/.cache/npm --global
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - npm install -g npm
    - yarn install
  script:
    - yarn build
    - mv public public_org && mv dist public
  artifacts:
    paths:
      - public
    